START TRANSACTION;

INSERT INTO Clans (ClanName)
VALUES
    ('Aburame'),
    ('Akimichi'),
    ('Amagiri'),
    ('Chinoike'),
    ('Fūma'),
    ('Funato'),
    ('Hagoromo'),
    ('Hatake'),
    ('Hirasaka'),
    ('Hoshigaki'),
    ('Hōzuki'),
    ('Hyūga'),
    ('Iburi'),
    ('Inuzuka'),
    ('Izuno'),
    ('Jūgo'),
    ('Kaguya'),
    ('Kamizuru'),
    ('Kedōin'),
    ('Kodon'),
    ('Kohaku'),
    ('Kumanoi'),
    ('Kurama'),
    ('Lee'),
    ('Nara'),
    ('Onikuma'),
    ('Ōtsutsuki'),
    ('Rinha'),
    ('Ryū'),
    ('Sarutobi'),
    ('Sendō'),
    ('Senju'),
    ('Shiin'),
    ('Shimura'),
    ('Shirogane'),
    ('Taketori'),
    ('Tenrō'),
    ('Tsuchigumo'),
    ('Uchiha'),
    ('Uzumaki'),
    ('Yamanaka'),
    ('Yoimura');
    
    
INSERT INTO Classes (ClassName) VALUES
    ('Ninjutsu Specialist'),
    ('Taijutsu Specialist'),
    ('Genjutsu Specialist'),
    ('Elemental Specialist'),
    ('Sealing Specialist'),
    ('Reconnaissance'),
    ('Swordsman'),
    ('Weapons Artisan'),
    ('Medic'),
    ('Puppeteer'),
    ('Sensor'),
    ('Tactician'),
    ('Animalist'),
    ('Demolitionist'),
    ('Tracker'),
    ('Brawler'),
    ('Wild Tamer'),
    ('Conjuror');

INSERT INTO ProficiencyTypes (ProficiencyName)
VALUES
    ('Acrobatics'),
    ('Animal Handling'),
    ('Athletics'),
    ('Deception'),
    ('History'),
    ('Insight'),
    ('Intimidation'),
    ('Investigation'),
    ('Nature'),
    ('Perception'),
    ('Performance'),
    ('Persuasion'),
    ('SleightOfHand'),
    ('Stealth'),
    ('Survival'),
    ('Tracking'),
    ('Ninjutsu'),
    ('Taijutsu'),
    ('Genjutsu'),
    ('Kenjutsu'),
    ('Shurikenjutsu'),
    ('Iryojutsu'),
    ('Fuinjutsu');


    INSERT INTO Ranks (RankName) VALUES
        ('Academy Student'),
        ('Genin'),
        ('Chunin'),
        ('Jonin'),
        ('Anbu'),
        ('Kage');
COMMIT;